### ISSUE TITLE
Usage of livesplit-core

### ISSUE THREAD

**Issue by CryZe** [MichaelJBerk/Splitter#1]
Hey, I just found your new timer on Reddit and it looks pretty cool. And I found the GitHub repository for it as well and it looks like you are making use of livesplit-core, which is pretty neat. However you only seem to be using it for LiveSplit split files. However it can actually parse pretty much every split file format that we are aware of, so you don't actually need to implement any others yourself (such as the splits.io exchange format). Though you totally can, as especially for the splits.io exchange format we don't extract all the information it can have. Additionally I'm wondering if you are planning on using livesplit-core for other parts of the timer as we can do all the timing and implement all the LiveSplit components for easy consumption for any kind of frontend.

**Comment by MichaelJBerk** [comment]
I currently use LiveSplit Core for LiveSplit files, and I plan to use it in the future for importing other formats as well. 

When I first started this project, I couldn't quite get LiveSplit Core to work with it, but now that have gotten it to work, I'd like to use it in the future when it makes the most sense to.
