### ISSUE TITLE
Scrolling (with the touchpad) to the top of the splits breifly shows second split at top

### ISSUE THREAD

**Issue by b-jazz** [MichaelJBerk/Splitter#130]
It looks like you can scroll beyond the top, but if you pay close attention, it really scrolls down a line as you two-finger scroll "up" and then when you release it pops back to the first line. I hope that makes sense. 

I have my prefs configured such that two fingers moving up the touchpad move the contents of the window up, if that makes a difference.

**Comment by MichaelJBerk** [comment]
This isn't an issue with macOS preferences - this is a bug with how I've set the splits table is set to scroll row-by-row.
