### ISSUE TITLE
Keep fixed time as comparison

### ISSUE THREAD

**Issue by jannismain** [MichaelJBerk/Splitter#139]
I would like to use Splitter to run against a fixed time per segment. Currently, I don't see any way for me to define a fixed time that each run is compared against. Is this possible and I'm just missing the right configuration, or would this be a new feature?

**Comment by MichaelJBerk** [comment]
I've added basic support for custom comparisons in the 6.0 beta - would that do the trick?

**Comment by jannismain** [comment]
I've tried the most recent beta and did not find a way to configure it, so that
- I have a fixed segment time column that never updates
- Have a Delta time column that is showing the delta compared to the fixed segment
- Does behave the same every time I run it

I'll be honest: I'm trying to run meetings using Splitter, which is probably not a use case that you want to support.

![SCR-20230505-otbk](https://github.com/MichaelJBerk/Splitter/assets/14290527/1458de39-5f29-4d0f-b6ab-d048c4094ab5)

In the meantime, I have coded up something that I can customize freely:

![SCR-20230505-ncwa](https://github.com/MichaelJBerk/Splitter/assets/14290527/643d9ccd-f31c-4ea1-8e42-fe203e1eba78)
→ [jannismain/smart-agenda](https://github.com/jannismain/smart-agenda)

So, thank you for your consideration, but I don't think Splitter is the best choice for my use case after all.
