### ISSUE TITLE
Hiding splits header leaves empty space

### ISSUE THREAD

**Issue by jannismain** [MichaelJBerk/Splitter#140]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/14290527/182933476-1621df43-b6af-4cb0-8027-6d25d11f3acd.png">

For me, hiding the header would only make sense, if the space that used to be occupied by the header would be removed and the list items would reach all the way to the top.

Restarting Splitter after hiding the header also doesn't change the layout

**Comment by MichaelJBerk** [comment]
This is fixed in build 281
