### ISSUE TITLE
Splits list scrolls regardless of required space

### ISSUE THREAD

**Issue by jannismain** [MichaelJBerk/Splitter#142]
I have a Splits list that still has space at the bottom of the list:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/14290527/182934378-55928efe-4a79-4746-bd75-9a4c2590b50b.png">

However, the list still scrolls, so that the top-most item might be hidden:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/14290527/182934391-c3dd3a73-5dea-4130-9ab4-be7ad2c300de.png">

**Comment by jannismain** [comment]
when there is even more space at the bottom, this doesn't happen:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/14290527/182934535-bb210714-ab0b-47a9-b1ed-a240bf62de11.png">

**Comment by MichaelJBerk** [comment]
This is fixed in build 281
