### ISSUE TITLE
Add option to show best possible time

### ISSUE THREAD

**Issue by MichaelJBerk** [MichaelJBerk/Splitter#95]

**Comment by b-jazz** [comment]
Can this be reopened? I don’t see that this was actually implemented and there is too associated commit so I can’t see where I’m the code it was added. I see that “sum of best segments” was added, but best possible time is slightly different. That stat should show what your time would be if you took your current run time and finished the rest of the segments with your gold times. Am I missing something or did this not get implemented yet?
